// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbsgen

import "strconv"

type EdgeType int8

const (
	EdgeTypeImport     EdgeType = 0
	EdgeTypeExtends    EdgeType = 1
	EdgeTypeImplements EdgeType = 2
	EdgeTypeCall       EdgeType = 3
	EdgeTypeReference  EdgeType = 4
	EdgeTypeForeignKey EdgeType = 5
)

var EnumNamesEdgeType = map[EdgeType]string{
	EdgeTypeImport:     "Import",
	EdgeTypeExtends:    "Extends",
	EdgeTypeImplements: "Implements",
	EdgeTypeCall:       "Call",
	EdgeTypeReference:  "Reference",
	EdgeTypeForeignKey: "ForeignKey",
}

var EnumValuesEdgeType = map[string]EdgeType{
	"Import":     EdgeTypeImport,
	"Extends":    EdgeTypeExtends,
	"Implements": EdgeTypeImplements,
	"Call":       EdgeTypeCall,
	"Reference":  EdgeTypeReference,
	"ForeignKey": EdgeTypeForeignKey,
}

func (v EdgeType) String() string {
	if s, ok := EnumNamesEdgeType[v]; ok {
		return s
	}
	return "EdgeType(" + strconv.FormatInt(int64(v), 10) + ")"
}
