// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbsgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Edge struct {
	_tab flatbuffers.Table
}

func GetRootAsEdge(buf []byte, offset flatbuffers.UOffsetT) *Edge {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Edge{}
	x.Init(buf, n+offset)
	return x
}

func FinishEdgeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEdge(buf []byte, offset flatbuffers.UOffsetT) *Edge {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Edge{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEdgeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Edge) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Edge) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Edge) TargetId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Edge) Type() EdgeType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return EdgeType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Edge) MutateType(n EdgeType) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

func (rcv *Edge) Confidence() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Edge) MutateConfidence(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func EdgeStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func EdgeAddTargetId(builder *flatbuffers.Builder, targetId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(targetId), 0)
}
func EdgeAddType(builder *flatbuffers.Builder, type_ EdgeType) {
	builder.PrependInt8Slot(1, int8(type_), 0)
}
func EdgeAddConfidence(builder *flatbuffers.Builder, confidence float32) {
	builder.PrependFloat32Slot(2, confidence, 0.0)
}
func EdgeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
