// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fbsgen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Shard struct {
	_tab flatbuffers.Table
}

func GetRootAsShard(buf []byte, offset flatbuffers.UOffsetT) *Shard {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Shard{}
	x.Init(buf, n+offset)
	return x
}

func FinishShardBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsShard(buf []byte, offset flatbuffers.UOffsetT) *Shard {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Shard{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedShardBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Shard) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Shard) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Shard) PackagePrefix() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Shard) Generation() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Shard) MutateGeneration(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *Shard) Nodes(obj *Node, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Shard) NodesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ShardStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ShardAddPackagePrefix(builder *flatbuffers.Builder, packagePrefix flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(packagePrefix), 0)
}
func ShardAddGeneration(builder *flatbuffers.Builder, generation uint64) {
	builder.PrependUint64Slot(1, generation, 0)
}
func ShardAddNodes(builder *flatbuffers.Builder, nodes flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(nodes), 0)
}
func ShardStartNodesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ShardEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
