#!/bin/sh
# graphin binary installer.
#
# Called by bin/graphin-launch.sh (synchronously, before the server starts),
# by hooks/session-start.sh (as a preheater), and by /graphin:setup.
# Safe to run concurrently: an mkdir lock serialises the real work and every
# caller re-checks the fast path after acquiring it.
#
# Everything lands in ${CLAUDE_PLUGIN_DATA}, never in the plugin directory —
# a plugin update replaces the plugin directory and would re-download 25MB
# every time.
#
# GRAPHIN_FORCE_INSTALL=1 skips the fast path (this is what /graphin:setup does).

set -eu

ROOT="${CLAUDE_PLUGIN_ROOT:?graphin: CLAUDE_PLUGIN_ROOT is unset}"
DATA="${CLAUDE_PLUGIN_DATA:-${XDG_DATA_HOME:-$HOME/.local/share}/graphin}"

MANIFEST="$ROOT/install/manifest.json"
BINDIR="$DATA/bin"
STATE="$DATA/state"
LINK="$BINDIR/graphin"
LOCK="$STATE/install.lock"
ERRFILE="$STATE/last-error.txt"

mkdir -p "$BINDIR" "$STATE" "$DATA/logs"

# GRAPHIN_INSTALL_CALLER identifies which entry point ran us. The launcher and
# the SessionStart hook race by design (their order is unspecified), and
# without this the log cannot say which one won — the difference is whether a
# first run is smooth or needs an /mcp reconnect.
CALLER="${GRAPHIN_INSTALL_CALLER:-direct}"

log() { printf '[%s] (%s) %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$CALLER" "$1"; }

# fail writes the reason where three different readers look for it: the
# launcher prints it to stderr, /graphin:doctor reads the file, and the log
# keeps the history.
fail() {
  printf 'graphin: %s\n' "$1" > "$ERRFILE"
  log "FAILED: $1"
  exit 1
}

have_sha256() {
  command -v sha256sum > /dev/null 2>&1 || command -v shasum > /dev/null 2>&1
}

sha256_of() {
  if command -v sha256sum > /dev/null 2>&1; then
    sha256sum "$1" | cut -d' ' -f1
  elif command -v shasum > /dev/null 2>&1; then
    shasum -a 256 "$1" | cut -d' ' -f1
  else
    return 1
  fi
}

# ── manifest readers ─────────────────────────────────────────────────────────
# The manifest is generated by our own release workflow with jq, so these read
# that known layout rather than parsing JSON in general.

# json_str <key> — first "key": "value" anywhere. Only used for keys that
# appear exactly once (version, repo, tag, module, min_go).
json_str() {
  sed -n 's/.*"'"$1"'": *"\([^"]*\)".*/\1/p' "$MANIFEST" | head -n1
}

# json_platform <platform> <key> — a key inside one platform's block.
json_platform() {
  awk -v pkey="\"$1\":" -v want="\"$2\":" '
    index($0, pkey) { inblock = 1; next }
    inblock && index($0, want) {
      rest = substr($0, index($0, want) + length(want))
      if (match(rest, /"[^"]*"/)) {
        print substr(rest, RSTART + 1, RLENGTH - 2)
        exit
      }
    }
    inblock && index($0, "}") { exit }
  ' "$MANIFEST"
}

# ── 0. Escape hatch ──────────────────────────────────────────────────────────
# The launcher already honours binary_path; this covers direct invocation.
if [ -n "${GRAPHIN_BIN:-}" ] && [ -x "${GRAPHIN_BIN}" ]; then
  log "using GRAPHIN_BIN=$GRAPHIN_BIN, nothing to install"
  exit 0
fi

# ── 1. Fast path ─────────────────────────────────────────────────────────────
up_to_date() {
  [ -z "${GRAPHIN_FORCE_INSTALL:-}" ] &&
    [ -x "$LINK" ] &&
    cmp -s "$MANIFEST" "$STATE/manifest.json"
}
if up_to_date; then
  exit 0
fi

if [ ! -r "$MANIFEST" ]; then
  fail "no install manifest at $MANIFEST — this plugin checkout predates its first release.
graphin:   Point the plugin's binary_path option at a locally built binary (make build),
graphin:   or reinstall the plugin once a release exists."
fi

# ── platform ─────────────────────────────────────────────────────────────────
case "$(uname -s)" in
  Linux) goos=linux ;;
  Darwin) goos=darwin ;;
  *) goos="$(uname -s | tr '[:upper:]' '[:lower:]')" ;;
esac
case "$(uname -m)" in
  x86_64 | amd64) goarch=amd64 ;;
  aarch64 | arm64) goarch=arm64 ;;
  *) goarch="$(uname -m)" ;;
esac
platform="$goos/$goarch"

VERSION="$(json_str version)"
REPO="$(json_str repo)"
TAG="$(json_str tag)"
ASSET="$(json_platform "$platform" asset)"
WANT_SHA="$(json_platform "$platform" sha256)"
BINNAME="$(json_platform "$platform" bin)"
[ -n "$BINNAME" ] || BINNAME="graphin"

if [ -z "$VERSION" ] || [ -z "$REPO" ] || [ -z "$TAG" ]; then
  fail "manifest at $MANIFEST is missing version/repo/tag — refusing to guess"
fi

# The versioned filename plus a symlink is not decoration: overwriting a
# running binary in place is ETXTBSY on Linux, while swapping the link leaves
# a running server holding the old inode until it exits on its own.
TARGET="$BINDIR/graphin-$VERSION-$goos-$goarch"

# ── lock ─────────────────────────────────────────────────────────────────────
# mkdir, not flock: flock is not portable to macOS.
waited=0
while ! mkdir "$LOCK" 2> /dev/null; do
  waited=$((waited + 1))
  if [ "$waited" -gt 600 ]; then
    fail "another install has held $LOCK for 10 minutes; delete it if it is stale"
  fi
  sleep 1
done
trap 'rmdir "$LOCK" 2>/dev/null || true' EXIT INT TERM HUP

# Someone else may have finished while we waited on the lock.
if up_to_date; then
  exit 0
fi

log "installing graphin $VERSION for $platform"

# ── 2. Relink ────────────────────────────────────────────────────────────────
# Upgrade → rollback → upgrade is a normal cycle; do not re-download a file
# that is already sitting there intact.
relink() {
  [ ! -d "$LINK" ] || fail "$LINK is a directory; move it aside"
  ln -s "$TARGET" "$LINK.tmp.$$"
  mv -f "$LINK.tmp.$$" "$LINK"
}

record() { # record <source>
  bsha="$(sha256_of "$TARGET" || echo unknown)"
  cat > "$STATE/installed.json" <<EOF
{
  "version": "$VERSION",
  "platform": "$platform",
  "file": "$TARGET",
  "sha256": "$bsha",
  "source": "$1",
  "installed_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
EOF
  # The manifest copy is the reinstall trigger, so it is written last and only
  # after everything else succeeded. A half-installed state must never look
  # up to date.
  cp "$MANIFEST" "$STATE/manifest.json"
  rm -f "$ERRFILE"
}

# Old versions are pruned: they are 25MB each, and unlinking a file a process
# is still executing is safe on Linux. A server started from a pruned file
# keeps running; its .graphin/binpath goes stale, which is exactly why
# hooks/usage.sh resolves the symlink before binpath.
prune() {
  for old in "$BINDIR"/graphin-*-"$goos"-"$goarch"; do
    if [ ! -e "$old" ] || [ "$old" = "$TARGET" ]; then
      continue
    fi
    rm -f "$old"
    log "pruned $old"
  done
}

if [ -x "$TARGET" ]; then
  known="$(sed -n 's/.*"sha256": *"\([^"]*\)".*/\1/p' "$STATE/installed.json" 2> /dev/null | head -n1)"
  actual="$(sha256_of "$TARGET" 2> /dev/null || echo unknown)"
  if [ -n "$known" ] && [ "$known" != "unknown" ] && [ "$known" = "$actual" ]; then
    relink
    record "relink"
    log "relinked existing $TARGET"
    exit 0
  fi
  log "existing $TARGET failed its recorded checksum; reinstalling"
  rm -f "$TARGET"
fi

# ── 3. Download ──────────────────────────────────────────────────────────────
download_release() {
  if [ -z "$ASSET" ] || [ -z "$WANT_SHA" ]; then
    log "no release asset pinned for $platform"
    return 1
  fi
  if ! command -v curl > /dev/null 2>&1; then
    log "curl not found"
    return 1
  fi
  if ! have_sha256; then
    # No checksum tool means no verification, and an unverified 25MB binary is
    # not something to install quietly.
    log "neither sha256sum nor shasum found; refusing to install unverified bytes"
    return 1
  fi

  tmp="$STATE/dl.$$"
  rm -rf "$tmp"
  mkdir -p "$tmp"

  url="https://github.com/$REPO/releases/download/$TAG/$ASSET"
  log "downloading $url"
  if ! curl -fsSL --proto '=https' --tlsv1.2 --retry 3 --max-time 600 \
    -o "$tmp/$ASSET" "$url"; then
    rm -rf "$tmp"
    log "download failed"
    return 1
  fi

  got="$(sha256_of "$tmp/$ASSET")"
  if [ "$got" != "$WANT_SHA" ]; then
    rm -rf "$tmp"
    # A partial or tampered install is worse than no install.
    fail "checksum mismatch for $ASSET
graphin:   want $WANT_SHA
graphin:   got  $got"
  fi

  if ! tar -xzf "$tmp/$ASSET" -C "$tmp"; then
    rm -rf "$tmp"
    log "could not extract $ASSET"
    return 1
  fi
  if [ ! -f "$tmp/$BINNAME" ]; then
    rm -rf "$tmp"
    log "$BINNAME missing from $ASSET"
    return 1
  fi

  chmod 0755 "$tmp/$BINNAME"
  mv -f "$tmp/$BINNAME" "$TARGET"
  rm -rf "$tmp"
  return 0
}

# ── 4. go install fallback ───────────────────────────────────────────────────
# Self-contained because the repository is public: no source copy, no
# checkout reference.
go_install() {
  command -v go > /dev/null 2>&1 || {
    log "go not found"
    return 1
  }
  if ! { command -v cc || command -v gcc || command -v clang; } > /dev/null 2>&1; then
    # tree-sitter and its grammars are cgo; onnxruntime_go links -ldl.
    log "no C compiler found (cc/gcc/clang); graphin cannot be built without one"
    return 1
  fi
  # go.mod requires a recent Go, so an older toolchain has to promote itself.
  if [ "$(go env GOTOOLCHAIN 2> /dev/null || echo auto)" = "local" ]; then
    log "GOTOOLCHAIN=local blocks the self-upgrade go.mod needs; unset it or install a newer Go"
    return 1
  fi

  module="$(json_str module)"
  [ -n "$module" ] || {
    log "manifest has no go_install.module"
    return 1
  }

  gobin="$STATE/gobin.$$"
  rm -rf "$gobin"
  mkdir -p "$gobin"
  log "go install $module@$TAG (this compiles C; it takes a while)"
  if ! GOBIN="$gobin" GOTOOLCHAIN=auto CGO_ENABLED=1 go install "$module@$TAG"; then
    rm -rf "$gobin"
    log "go install failed"
    return 1
  fi
  if [ ! -x "$gobin/graphin" ]; then
    rm -rf "$gobin"
    log "go install produced no graphin binary"
    return 1
  fi

  # This binary came from outside, so its identity is checked by asking it —
  # the one case where --version is the right tool. ldflags are absent on this
  # path, which is why `graphin version` falls back to the embedded build info.
  got="$("$gobin/graphin" version --json 2> /dev/null | sed -n 's/.*"version": *"\([^"]*\)".*/\1/p')"
  case "$got" in
    "$VERSION" | "v$VERSION") ;;
    *)
      rm -rf "$gobin"
      log "go install produced version '$got', expected $VERSION"
      return 1
      ;;
  esac

  mv -f "$gobin/graphin" "$TARGET"
  rm -rf "$gobin"
  return 0
}

source=""
if download_release; then
  source="release"
elif go_install; then
  source="go-install"
else
  if [ -z "$ASSET" ]; then
    fail "no graphin release is published for $platform, and building from source failed.
graphin:   Build it yourself (git clone + make build) and set the plugin's binary_path option.
graphin:   Details: $DATA/logs/install.log"
  fi
  fail "could not install graphin $VERSION for $platform — download and go install both failed.
graphin:   Details: $DATA/logs/install.log"
fi

relink
record "$source"
prune
log "installed graphin $VERSION from $source at $TARGET"
