package wiki

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// PushCap bounds one role's generated block.
//
// A push block is paid for on every session of every agent that carries it,
// whether or not it is read, and that is the opposite of the catalogue's
// economics. Past some size a standing block stops being read at all, so a
// wiki that outgrows this must choose — which is a decision, and decisions
// belong to people. Overflow is reported, never silently trimmed.
const PushCap = 12

// GeneratedSkill is one role's convention block.
type GeneratedSkill struct {
	Role string
	// Name is the skill directory and its `name:` field.
	Name string
	Body string
	// Dropped names what did not fit under PushCap. A cap that trims in
	// silence reads as "this is everything", which is the one thing a
	// standing block must not imply.
	Dropped []string
}

// Roles lists every role the wiki tags, in name order.
//
// "all" is not a role here: it is a wildcard that lands in every role's block,
// so emitting a skill for it would duplicate the same text under a name no
// agent is assigned.
func (st *Store) Roles() []string {
	seen := map[string]bool{}
	for _, s := range st.SetList() {
		for _, r := range s.Roles {
			if !strings.EqualFold(r, "all") {
				seen[strings.ToLower(r)] = true
			}
		}
	}
	for _, t := range st.Terms {
		for _, r := range t.Scope {
			if !strings.EqualFold(r, "all") {
				seen[strings.ToLower(r)] = true
			}
		}
	}
	out := make([]string, 0, len(seen))
	for r := range seen {
		out = append(out, r)
	}
	sort.Strings(out)
	return out
}

// termsForRole returns the glossary entries a role carries, in name order.
func (st *Store) termsForRole(role string) []*Term {
	names := make([]string, 0, len(st.Terms))
	for n := range st.Terms {
		names = append(names, n)
	}
	sort.Strings(names)

	var out []*Term
	for _, n := range names {
		t := st.Terms[n]
		if t.Status == StatusDraft {
			continue
		}
		for _, s := range t.Scope {
			if strings.EqualFold(s, role) || strings.EqualFold(s, "all") {
				out = append(out, t)
				break
			}
		}
	}
	return out
}

// GenerateSkill builds one role's block.
//
// Set bodies are never copied in. A skill is procedural knowledge and a set is
// declarative; duplicating the second into the first creates two copies of one
// fact, and the copy in the skill is the one that goes stale unseen. Terms are
// the exception and carry their definitions, because a reader who does not know
// they are using the wrong word will not go looking for the right one.
func (st *Store) GenerateSkill(role string) GeneratedSkill {
	g := GeneratedSkill{Role: role, Name: role + "-conventions"}
	terms := st.termsForRole(role)
	sets := st.ForRole(role)

	budget := PushCap
	if len(terms) > budget {
		for _, t := range terms[budget:] {
			g.Dropped = append(g.Dropped, "term "+t.Canonical)
		}
		terms = terms[:budget]
	}
	budget -= len(terms)
	if len(sets) > budget {
		for _, s := range sets[budget:] {
			g.Dropped = append(g.Dropped, "set "+s.Name)
		}
		sets = sets[:budget]
	}

	var b strings.Builder
	b.WriteString("---\nname: " + g.Name + "\n")
	b.WriteString("description: >-\n  The standing rules and vocabulary for " + role +
		" work in this project. Injected in full at the start of every " + role +
		"\n  session, so it names what an agent cannot know it is missing.\n---\n\n")
	b.WriteString("<!--\n  Generated by `graphin wiki skills`. Edits here are overwritten;\n" +
		"  change docs/wiki/ instead and regenerate.\n-->\n\n")
	fmt.Fprintf(&b, "# %s conventions\n\n", strings.ToUpper(role[:1])+role[1:])

	if len(terms) > 0 {
		b.WriteString("## Words this project uses precisely\n\n")
		for _, t := range terms {
			fmt.Fprintf(&b, "- **%s**", t.Canonical)
			if len(t.Aliases) > 0 {
				fmt.Fprintf(&b, " (also: %s)", strings.Join(t.Aliases, ", "))
			}
			fmt.Fprintf(&b, " — %s\n", firstSentence(t.Body))
			for _, c := range t.Confusions {
				fmt.Fprintf(&b, "  - Not **%s**: %s\n", c.Term, c.Why)
			}
		}
		b.WriteString("\n")
	}

	if len(sets) > 0 {
		b.WriteString("## Background this role is expected to have\n\n")
		b.WriteString("Load what the work needs; do not load all of it.\n\n")
		for _, s := range sets {
			fmt.Fprintf(&b, "- `%s` (%d entries) — %s\n", s.Name, len(s.Entries()), firstSentence(s.Summary()))
		}
		b.WriteString("\nFetch with `wiki_resolve(sets=[…])`. The catalogue lives at " +
			"`docs/wiki/sets/`, and each set is a section node you can read directly.\n\n")
	}

	if len(g.Dropped) > 0 {
		// Say it in the artifact, not only in the generator's output: whoever
		// reads this block later is the one who needs to know it is partial.
		fmt.Fprintf(&b, "> This block is capped at %d items and %d did not fit "+
			"(%s). Narrow the role tags in `docs/wiki/` rather than assuming this is everything.\n\n",
			PushCap, len(g.Dropped), strings.Join(g.Dropped, ", "))
	}

	if len(terms) == 0 && len(sets) == 0 {
		b.WriteString("Nothing is tagged for this role yet.\n")
	}
	g.Body = b.String()
	return g
}

// WriteSkills generates every role's block under dir and returns what it
// wrote. Existing files are replaced; the generator owns them.
func (st *Store) WriteSkills(dir string) ([]GeneratedSkill, error) {
	roles := st.Roles()
	out := make([]GeneratedSkill, 0, len(roles))
	for _, r := range roles {
		g := st.GenerateSkill(r)
		path := filepath.Join(dir, g.Name, "SKILL.md")
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return nil, err
		}
		if err := os.WriteFile(path, []byte(g.Body), 0o644); err != nil {
			return nil, err
		}
		out = append(out, g)
	}
	return out, nil
}

// StaleSkills lists roles whose generated file is missing or out of date.
// A generated artifact that drifts from its source is worse than none: it
// still looks authoritative.
func (st *Store) StaleSkills(dir string) []string {
	var stale []string
	for _, r := range st.Roles() {
		g := st.GenerateSkill(r)
		raw, err := os.ReadFile(filepath.Join(dir, g.Name, "SKILL.md"))
		if err != nil || string(raw) != g.Body {
			stale = append(stale, g.Name)
		}
	}
	return stale
}

// AgentsNeeding maps each generated skill to the agents that should declare
// it, from the same table the gate uses.
//
// It reports rather than edits. Agent definitions are the user's files, and a
// generator that rewrites them turns "regenerate" into an action nobody can
// safely run without reading the diff first.
func (st *Store) AgentsNeeding() map[string][]string {
	out := map[string][]string{}
	for name, role := range st.Agents.roles {
		if strings.EqualFold(role, RoleExempt) || role == "" {
			continue
		}
		skill := strings.ToLower(role) + "-conventions"
		out[skill] = append(out[skill], name)
	}
	for _, agents := range out {
		sort.Strings(agents)
	}
	return out
}
